### ISSUE TITLE
Exclude `zh/modules-reference/diagrams` for permalink

### ISSUE THREAD

**Issue by awxiaoxian2020** [ts-zh-docs/TypeScript-Website#61]
https://github.com/ts-zh-docs/TypeScript-Website/blob/236f0f8ab2bc1d63dd0162dc9566b573d558dd47/packages/typescriptlang-org/lib/bootup/ingestion/createPagesForDocumentation.ts#L26

Here we only exclude `en`, we need exclude `zh` too.

related to https://github.com/ts-zh-docs/TypeScript-zh-Website/pull/66

**Comment by awxiaoxian2020** [comment]
@andrewbranch we are not familiar with graphql. Could you help us for this? :)

**Comment by andrewbranch** [comment]
Could you please clarify what you need me to do?

**Comment by awxiaoxian2020** [comment]
Hi, @andrewbranch I just want to add something like 

`relativeDirectory: { ne: "zh/modules-reference/diagrams" } ` 

to pass the build in https://github.com/ts-zh-docs/TypeScript-zh-Website/pull/66

**Comment by awxiaoxian2020** [comment]
I fix it in #62 but it too slow for graph query...
